name: Intentional Failure

on:
  push:
    branches:
      - testbranch


jobs:
  fail-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with: 
          token: ${{secrets.GITHUB_TOKEN}}

      - name: Run the failing command
        run: exit 1  # This command will cause the workflow to fail
